conn "sjtu-student"
    keyexchange=ikev2
    left=%config
    leftsourceip=%config4,%config6
    leftauth=eap-peap

    right=stu.vpn.sjtu.edu.cn
    rightid=@stu.vpn.sjtu.edu.cn
    rightsendcert=never

    rightsubnet=0.0.0.0/0,2000::/3
    rightauth=pubkey
    eap_identity=%SJTU_USERNAME%
    aaa_identity="@radius.net.sjtu.edu.cn"
    auto=add